apiVersion: v1
kind: Pod
metadata:
  name: hm-sqlite-debug
  namespace: hm
spec:
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  volumes:
    - name: app-root
      persistentVolumeClaim:
        claimName: hm-app-root
  containers:
    - name: debug
      image: keinos/sqlite3:latest
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command: ["/bin/sh","-lc"]
      args: ["sleep 3600"]
      volumeMounts:
        - name: app-root
          mountPath: /app
