apiVersion: v1
kind: Pod
metadata:
  name: hm-sqlite-work
  namespace: hm
spec:
  restartPolicy: Never
  nodeName: mediatriplem4
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  volumes:
    - name: app-root
      persistentVolumeClaim:
        claimName: hm-app-root
  containers:
    - name: work
      image: debian:bookworm-slim
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      command: ["/bin/sh","-lc"]
      args: ["sleep 3600"]
      volumeMounts:
        - name: app-root
          mountPath: /app
