apiVersion: apps/v1
kind: Deployment
metadata:
  name: hm-worker-ingest
  namespace: hm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hm-worker-ingest
  template:
    metadata:
      labels:
        app: hm-worker-ingest
    spec:
      nodeName: mediatriplem4
      imagePullSecrets:
        - name: my-dockerhub-secret
      volumes:
        - name: app-root
          persistentVolumeClaim:
            claimName: hm-app-root
      containers:
        - name: worker
          image: mediatriple/hm:0.7.6
          command: ["python", "scripts/worker_ingest.py"]
          workingDir: /app
          env:
            - name: PYTHONPATH
              value: /app
            - name: REDIS_URL
              value: redis://hm-redis.hm.svc.cluster.local:6379/0
            - name: MEDIA_ROOT
              value: /app/data/media
            - name: THUMBS_ROOT
              value: /app/data/thumbs
            - name: OPENAI_API_KEY
              valueFrom: { secretKeyRef: { name: hm-openai, key: OPENAI_API_KEY } }
            - name: IG_APP_SECRET
              valueFrom: { secretKeyRef: { name: hm-ig, key: IG_APP_SECRET } }
            - name: IG_WEBHOOK_VERIFY_TOKEN
              valueFrom: { secretKeyRef: { name: hm-ig, key: IG_WEBHOOK_VERIFY_TOKEN } }
            - name: IG_PAGE_ID
              valueFrom: { secretKeyRef: { name: hm-ig, key: IG_PAGE_ID } }
            - name: IG_PAGE_ACCESS_TOKEN
              valueFrom: { secretKeyRef: { name: hm-ig, key: IG_PAGE_ACCESS_TOKEN } }
            - name: IG_USER_ID
              valueFrom: { secretKeyRef: { name: hm-ig, key: IG_USER_ID } }
            - name: IG_ACCESS_TOKEN
              valueFrom: { secretKeyRef: { name: hm-ig, key: IG_ACCESS_TOKEN } }
            - name: IG_GRAPH_API_VERSION
              value: v21.0
            - name: WA_PHONE_NUMBER_ID
              valueFrom: { secretKeyRef: { name: hm-ig, key: WA_PHONE_NUMBER_ID } }
            - name: WA_ACCESS_TOKEN
              valueFrom: { secretKeyRef: { name: hm-ig, key: WA_ACCESS_TOKEN } }
            - name: WA_BUSINESS_ACCOUNT_ID
              valueFrom: { secretKeyRef: { name: hm-ig, key: WA_BUSINESS_ACCOUNT_ID } }
            - name: WA_GRAPH_API_VERSION
              value: v22.0
            - name: DATABASE_URL
              value: "mysql+pymysql://hm:0Nh4shgeoYmhhe+!d@185.70.97.125:30336/appdb_h?charset=utf8mb4"
          volumeMounts:
            - name: app-root
              mountPath: /app
