name: hma_stock
description: HMA stok giriş/çıkış ve QR akışı
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  uuid: ^4.5.1
  mobile_scanner: ^7.2.0
  google_mlkit_text_recognition: ^0.15.0
  qr_flutter: ^4.1.0
  pdf: ^3.11.1
  printing: ^5.14.3
  flutter_tesseract_ocr: ^0.4.30
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tessdata_config.json
    - assets/tessdata/tur.traineddata
    - assets/tessdata/eng.traineddata
